#!/usr/bin/env node
// build-data.mjs
// Scans {dir}/src for .vue / .js / .less / .css / .json sources and (re)generates
// {dir}/preview-data.js — the source map consumed by index.gts.html to
// compile SFCs in the browser via vue3-sfc-loader.
//
// <style lang="less"> blocks in .vue files are compiled browser-side by less.js
// (loaded in index.gts.html). Imported .less files are handled by the
// handleModule .less handler (also using browser less.js).
//
// Also exported as a module function so build.mjs auto-runs it (standalone
// use is rarely needed).
//
// Usage:
//   node build-data.mjs --dir "{artifact-folder}/{slug}"
//
// Output (agent-parseable):
//   RESULT: OK
//   FILES: <count of embedded sources>
//   DATA_PATH: <absolute path to preview-data.js>
//   RESULT: FAIL | <reason>

import { existsSync, readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, resolve, dirname, extname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const TEXT_EXT = new Set(['.vue', '.js', '.mjs', '.css', '.less', '.json']);

export function collectSources(srcDir, mockDir) {
  const map = {};

  function walkAndCollect(dir, prefix) {
    const files = [];
    (function walk(d) {
      for (const entry of readdirSync(d, { withFileTypes: true })) {
        const full = join(d, entry.name);
        if (entry.isDirectory()) {
          if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
          walk(full);
        } else if (TEXT_EXT.has(extname(entry.name))) {
          files.push(full);
        }
      }
    })(dir);
    for (const f of files) {
      const rel = f.slice(dir.length).split('\\').join('/').replace(/^\/+/, '');
      map[prefix + rel] = readFileSync(f, 'utf8');
    }
  }

  walkAndCollect(srcDir, '/src/');
  if (mockDir && existsSync(mockDir) && statSync(mockDir).isDirectory()) {
    walkAndCollect(mockDir, '/mock/');
  }
  return map;
}

export function refresh(dir) {
  const root = resolve(dir);
  const srcDir = join(root, 'src');
  const mockDir = join(root, 'mock');
  if (!existsSync(srcDir) || !statSync(srcDir).isDirectory()) {
    return { ok: false, reason: `src folder not found: ${srcDir}` };
  }
  if (!existsSync(join(root, 'index.gts.html'))) {
    return { ok: false, reason: `index.gts.html not found: ${join(root, 'index.gts.html')}` };
  }
  const map = collectSources(srcDir, mockDir);
  if (!map['/src/App.vue']) {
    return { ok: false, reason: 'src/App.vue not found (preview entry)' };
  }
  const stamp = new Date().toISOString();
  const dataPath = join(root, 'preview-data.js');
  const body =
    `// AUTO-GENERATED by build-data.mjs (${stamp}) — do not edit\n` +
    `// key = path from src root; consumed by index.gts.html + vue3-sfc-loader\n` +
    `window.__GTS_SRC__ = ${JSON.stringify(map, null, 0)};\n` +
    `window.__GTS_REFRESHED_AT = ${JSON.stringify(stamp)};\n`;
  writeFileSync(dataPath, body, 'utf8');
  return { ok: true, count: Object.keys(map).length, dataPath };
}

// ---------- CLI ----------
if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  const args = process.argv.slice(2);
  const idx = args.findIndex((a) => a === '--dir' || a === '-d');
  const dir = idx !== -1 ? args[idx + 1] : undefined;
  if (!dir) {
    console.log('RESULT: FAIL | Usage: node build-data.mjs --dir "<folder with src/ and index.gts.html>"');
    process.exit(1);
  }
  const result = refresh(dir);
  if (!result.ok) {
    console.log(`RESULT: FAIL | ${result.reason}`);
    process.exit(1);
  }
  console.log('RESULT: OK');
  console.log(`FILES: ${result.count}`);
  console.log(`DATA_PATH: ${result.dataPath}`);
}
